# Generated by Django 4.0.5 on 2022-06-21 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('ODEZHDA', 'odezhda'), ('OBUV', 'Obuv'), ('BRUKI', 'Bruki'), ('SHAPKI', 'Shapki')], default='ODEZHDA', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.catalog')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('venCode', models.CharField(max_length=12)),
                ('image', models.ImageField(default='api/image/def.jpg', upload_to='api/image/')),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('RemaniningStock', models.FloatField()),
                ('sum', models.FloatField()),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.catalog')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
