# Generated by Django 4.0.5 on 2022-07-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_size_prod_rename_vencode_product_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size_prod',
            old_name='size',
            new_name='name',
        ),
    ]
