# Generated by Django 4.0.5 on 2022-07-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_size_size_prod_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size_prod',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
    ]
