# Generated by Django 4.0.5 on 2022-07-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_deliverycost_alter_cart_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycost',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='deliverycost',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
